# Generated by Django 5.1.9 on 2025-10-27 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='賽馬娘名稱')),
                ('rarity', models.CharField(choices=[('★1', '★1'), ('★2', '★2'), ('★3', '★3')], max_length=10)),
                ('distance_type', models.CharField(choices=[('短距離', '短距離'), ('一哩', '一哩'), ('中距離', '中距離'), ('長距離', '長距離')], max_length=20)),
                ('running_style', models.CharField(choices=[('逃げ', '逃げ'), ('先行', '先行'), ('差し', '差し'), ('追込', '追込')], max_length=20)),
                ('image_path', models.CharField(choices=[], help_text='從現有角色圖中選擇（static/horses/）', max_length=200, verbose_name='角色圖片')),
            ],
        ),
        migrations.CreateModel(
            name='SupportCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='卡組名稱')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sets', to='uma.horse')),
            ],
        ),
        migrations.CreateModel(
            name='SupportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('速度', '速度'), ('耐力', '耐力'), ('力量', '力量'), ('根性', '根性'), ('智慧', '智慧'), ('友情', '友情')], max_length=10, verbose_name='支援卡種類')),
                ('horse_name', models.CharField(max_length=50, verbose_name='馬娘名稱')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='uma.supportcardset')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='培育日期')),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('power', models.IntegerField()),
                ('guts', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('evaluation_score', models.IntegerField(verbose_name='總分')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='uma.horse')),
            ],
        ),
    ]
