# Generated by Django 5.1.9 on 2025-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='distance_type',
            field=models.CharField(choices=[('短距離', '短距離'), ('一哩', '一哩'), ('中距離', '中距離'), ('長距離', '長距離')], max_length=20, verbose_name='距離類型'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='rarity',
            field=models.CharField(choices=[('★1', '★1'), ('★2', '★2'), ('★3', '★3'), ('★4', '★4'), ('★5', '★5')], max_length=10, verbose_name='稀有度'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='running_style',
            field=models.CharField(choices=[('逃げ', '逃げ'), ('先行', '先行'), ('差し', '差し'), ('追込', '追込')], max_length=20, verbose_name='跑法'),
        ),
    ]
