# Generated by Django 5.1.9 on 2025-10-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0002_alter_horse_distance_type_alter_horse_rarity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horse',
            options={'verbose_name': '馬娘', 'verbose_name_plural': '馬娘'},
        ),
        migrations.AlterModelOptions(
            name='supportcard',
            options={'verbose_name': '支援卡', 'verbose_name_plural': '支援卡'},
        ),
        migrations.AlterModelOptions(
            name='trainingresult',
            options={'verbose_name': '培育結果', 'verbose_name_plural': '培育結果'},
        ),
        migrations.RemoveField(
            model_name='horse',
            name='image_path',
        ),
    ]
