# Generated by Django 5.1.9 on 2025-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0003_alter_horse_options_alter_supportcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcardset',
            name='name',
            field=models.CharField(default='未命名', max_length=100, verbose_name='卡組名稱'),
        ),
    ]
