# Generated by Django 5.1.9 on 2025-10-27 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0004_alter_supportcardset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingresult',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='uma.horse'),
        ),
    ]
